spring:
  profiles:
    # local = no signin, normal = signin
    default: local
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/db_oze?useTimezone=true&serverTimezone=UTC
    username: root
    password: pass
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

